name: DI
channels:
  - conda-forge
  - bioconda
  - defaults
  - http://statgen.org/wp-content/uploads/Softwares/pybgen
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.8=h166bdaf_0
  - anyio=4.4.0=pyhd8ed1ab_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h2372a71_4
  - arrow=1.3.0=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - babel=2.14.0=pyhd8ed1ab_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - bedtools=2.31.1=hf5e1c6e_1
  - biopython=1.83=py310h2372a71_0
  - bleach=6.1.0=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.28.1=hd590300_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=hbbf8b49_1016
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2fee648_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - conda=22.9.0=py310hff52083_2
  - conda-package-handling=2.4.0=pyh7900ff3_0
  - conda-package-streaming=0.11.0=pyhd8ed1ab_0
  - contourpy=1.2.1=py310hd41b1e2_0
  - cryptography=39.0.0=py310h65dfdc0_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - debugpy=1.8.5=py310hea249c9_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - expat=2.6.2=h59595ed_0
  - fastp=0.23.4=h5f740d0_0
  - fastqc=0.12.1=hdfd78af_0
  - fmt=9.1.0=h924138e_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_2
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py310h2372a71_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - future=1.0.0=pyhd8ed1ab_0
  - giflib=5.2.2=hd590300_0
  - graphite2=1.3.13=h59595ed_1003
  - h11=0.14.0=pyhd8ed1ab_0
  - h2=4.1.0=pyhd8ed1ab_0
  - harfbuzz=6.0.0=h3ff4399_1
  - hpack=4.0.0=pyh9f0ad1d_0
  - htslib=1.17=h6bc39ce_1
  - httpcore=1.0.5=pyhd8ed1ab_0
  - httpx=0.27.2=pyhd8ed1ab_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=72.1=hcb278e6_0
  - idna=3.7=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib_metadata=8.5.0=hd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.27.0=pyh707e725_0
  - isa-l=2.31.0=hd590300_1
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - json5=0.9.25=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310hff52083_1
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2023.12.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_0
  - jupyter-lsp=2.2.5=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py310hff52083_0
  - jupyter_events=0.10.0=pyhd8ed1ab_0
  - jupyter_server=2.14.2=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_0
  - jupyterlab=4.2.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_1
  - jupyterlab_server=2.27.3=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.20.1=hf9c8cef_0
  - lcms2=2.14=h6ed2654_0
  - ld_impl_linux-64=2.40=h55db66e_0
  - lerc=4.0.0=h27087fc_0
  - libarchive=3.6.2=hc8874e4_0
  - libblas=3.9.0=22_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=22_linux64_openblas
  - libcups=2.3.3=h36d4200_3
  - libcurl=7.88.1=h91b91d3_2
  - libdeflate=1.13=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h77fa898_7
  - libgfortran-ng=13.2.0=h69a702a_7
  - libgfortran5=13.2.0=hca663fb_7
  - libglib=2.80.2=hf974151_0
  - libgomp=13.2.0=h77fa898_7
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=22_linux64_openblas
  - libmamba=1.2.0=habaa8ee_0
  - libmambapy=1.2.0=py310h4d5d8b6_0
  - libnghttp2=1.52.0=ha637b67_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.27=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.29=ha6fb4c9_0
  - libsqlite=3.45.3=h2797004_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=13.2.0=hc0a3c3a_7
  - libtiff=4.4.0=h0e0dad5_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.11.5=h0d562d8_0
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=hd590300_1001
  - mamba=1.2.0=py310hf87f941_0
  - markupsafe=2.1.5=py310h2372a71_0
  - matplotlib-base=3.9.2=py310hf02ac8c_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mistune=3.0.2=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-connector-c=6.1.11=h6eb9d5d_1007
  - nbclient=0.10.0=pyhd8ed1ab_0
  - nbconvert-core=7.16.4=pyhd8ed1ab_1
  - nbformat=5.10.4=pyhd8ed1ab_0
  - ncurses=6.5=h59595ed_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.3=pyhd8ed1ab_1
  - notebook-shim=0.2.4=pyhd8ed1ab_0
  - numpy=1.26.4=py310hb13e2d6_0
  - openjdk=17.0.3=h58dac75_5
  - openjpeg=2.5.0=h7d73246_1
  - openssl=1.1.1w=hd590300_0
  - overrides=7.7.0=pyhd8ed1ab_0
  - packaging=24.0=pyhd8ed1ab_0
  - pandas=2.2.2=py310hf9f9076_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - perl=5.32.1=7_hd590300_perl5
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py310h5eee18b_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=5.9.8=py310h2372a71_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pybedtools=0.10.0=py310h2b6aa90_0
  - pybigwig=0.3.22=py310h722e95c_0
  - pybind11-abi=4=hd8ed1ab_3
  - pybktree=1.1=pyh9f0ad1d_0
  - pycosat=0.6.6=py310h2372a71_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pypints=1.1.10=pyh7cba7a3_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.8=h257c98d_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h5b4e0ec_0
  - pyzmq=26.2.0=py310h71f11fc_0
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - regex=2024.5.10=py310hc51659f_0
  - reproc=14.2.4.post0=hd590300_1
  - reproc-cpp=14.2.4.post0=h59595ed_1
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.20.0=py310h42e942d_0
  - ruamel_yaml=0.15.80=py310h2372a71_1009
  - samtools=1.18=hd87286a_0
  - send2trash=1.8.3=pyh0d859eb_0
  - setuptools=69.5.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - star=2.7.11a=h0033a41_0
  - statsmodels=0.14.1=py310h1f7b6fc_0
  - tabix=1.11=hdfd78af_0
  - terminado=0.18.1=pyh0d859eb_0
  - tinycss2=1.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.1=pyhd8ed1ab_0
  - toolz=1.0.0=pyhd8ed1ab_0
  - tornado=6.4.1=py310hc51659f_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - types-python-dateutil=2.9.0.20240906=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2024a=h0c530f3_0
  - ucsc-bigwigmerge=377=ha8a8165_3
  - ucsc-bigwigtobedgraph=377=ha8a8165_6
  - umi_tools=1.1.5=py310h4b81fae_1
  - unicodedata2=15.1.0=py310h2372a71_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - webcolors=24.8.0=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.8.0=pyhd8ed1ab_0
  - wheel=0.43.0=pyhd8ed1ab_1
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.9=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxtst=1.2.3=h7f98852_1002
  - xorg-recordproto=1.14.2=h7f98852_1002
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yaml-cpp=0.7.0=h59595ed_3
  - zeromq=4.3.5=h59595ed_1
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstandard=0.23.0=py310h64cae3c_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
    - alabaster==1.0.0
    - anndata==0.10.9
    - array-api-compat==1.9
    - asciitree==0.3.3
    - biodata==0.1.4
    - biodataplot==0.0.4
    - biodatatools==0.0.7
    - bioframe==0.7.2
    - boto3==1.35.39
    - botocore==1.35.39
    - bx-python==0.13.0
    - cachetools==4.2.4
    - click==8.1.7
    - colorama==0.4.6
    - commandtemplate==0.0.1
    - commonhelper==0.0.5
    - cooler==0.10.2
    - cooltools==0.7.1
    - cython==3.0.11
    - cytoolz==1.0.0
    - deeptools==3.5.5
    - deeptoolsintervals==0.1.9
    - dill==0.3.9
    - docutils==0.21.2
    - et-xmlfile==1.1.0
    - exifread==3.0.0
    - filelock==3.16.1
    - fsspec==2024.10.0
    - genomictools==0.0.8
    - h5py==3.12.1
    - hdf5plugin==5.0.0
    - hic-straw==1.3.1
    - httplib2==0.22.0
    - igraph==0.11.6
    - imageio==2.36.0
    - imagesize==1.4.1
    - inflection==0.5.1
    - jmespath==1.0.1
    - joblib==1.4.2
    - lazy-loader==0.4
    - leidenalg==0.10.2
    - llvmlite==0.43.0
    - logomaker==0.8
    - lxml==5.3.0
    - matplotlib-venn==1.1.1
    - modisco-lite==2.2.1
    - mphelper==0.0.3
    - mpmath==1.3.0
    - multiprocess==0.70.17
    - natsort==8.4.0
    - ncls==0.0.68
    - nodejs==0.1.1
    - numba==0.60.0
    - numpydoc==1.8.0
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - openpyxl==3.1.5
    - optional-django==0.1.0
    - plotly==5.24.1
    - protobuf==4.25.5
    - py2bit==0.3.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pybind11==2.13.6
    - pyfaidx==0.8.1.3
    - pyparsing==3.0.9
    - pyranges==0.1.2
    - pysam==0.22.1
    - rmsp==0.1.0
    - rsa==4.7.2
    - s3transfer==0.10.3
    - scikit-image==0.24.0
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - seaborn==0.13.2
    - simplejson==3.19.3
    - simplevc==0.0.3
    - snowballstemmer==2.2.0
    - sorted-nearest==0.0.39
    - sphinx==8.0.2
    - sphinxcontrib-applehelp==2.0.0
    - sphinxcontrib-devhelp==2.0.0
    - sphinxcontrib-htmlhelp==2.1.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==2.0.0
    - sphinxcontrib-serializinghtml==2.0.0
    # - statannotations==0.6.0 (see installation in data_preprocessing/2.Other_resources.ipynb to avoid incompatibility)
    - svgutils==0.3.4
    - sympy==1.13.1
    - tabulate==0.9.0
    - tagore==1.1.2
    - tenacity==9.0.0
    - texttable==1.7.0
    - threadpoolctl==3.5.0
    - tifffile==2024.9.20
    - torch==2.5.0
    - tqdm==4.66.5
    - triton==3.1.0
    - uritemplate==4.1.1
prefix: /home/yc2553/miniconda3_new/envs/DI
